### ISSUE TITLE
No need to iterate over get_users_by_capability() results

### ISSUE THREAD

**Issue by mudrd8mz** [andreasschenkel/moodle-block_course_list_advanced#8]
https://github.com/andreasschenkel/moodle-block_course_list_advanced/blob/3a6445a9f49394327482e2f87600d3b0b7d1891a/block_course_list_advanced.php#L126-L140

I don't think it is required to iterate over `get_users_by_capability()` results to seek if the current user is there.

Why not to so something simpler such as `has_capability()`?

**Comment by andreasschenkel** [comment]
solved with v2.0.5
